### ISSUE TITLE
Raspberry pi zero support

### ISSUE THREAD

**Issue by lazopm** [inre/cupi#2]
Are you planning on supporting it?

**Comment by inre** [comment]
Hello, thank you for question. I will add it when I get one. But you can fix it by yourself and just create a pull request.

**Comment by posborne** [comment]
If you need support today, you can also use https://github.com/rust-embedded/rust-sysfs-gpio which supports any device with a Linux kernel supporting the standard sysfs GPIO interface (so, any embedded device running a semi-modern kernel).

**Comment by inre** [comment]
We added Pi3/Zero boards. Enjoy.
